export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const VIEW_MY_ORDERS_REQUEST = "VIEW_MY_ORDERS_REQUEST";
export const VIEW_MY_ORDERS_SUCCESS = "VIEW_MY_ORDERS_SUCCESS";
export const VIEW_MY_ORDERS_FAILURE = "VIEW_MY_ORDERS_FAILURE";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILURE = "ORDER_DETAILS_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";