export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOAD_LOGGED_IN_USER_REQUEST = "LOAD_LOGGED_IN_USER_REQUEST";
export const LOAD_LOGGED_IN_USER_SUCCESS = "LOAD_LOGGED_IN_USER_SUCCESS";
export const LOAD_LOGGED_IN_USER_FAILURE = "LOAD_LOGGED_IN_USER_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";